services:
  pi:
    build: .
    image: pi
    stdin_open: true
    tty: true
    # extra_hosts:
    # - host.docker.internal:host-gateway
    volumes:
    - ./pi:/home/pi/.pi
    - ./skills:/home/pi/.pi/agent/skills
    - ./workspace:/workspace
    environment:
    - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
    - RDMO_URL=${RDMO_URL:-}
    - RDMO_TOKEN=${RDMO_TOKEN:-}
    working_dir: /workspace
